# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
default: true
MD013:
  # Number of characters
  line_length: 100
  # Include code blocks
  code_blocks: false
  # Include tables
  tables: false
