version: "2.4"
services:
  aten:
    build:
      # docker-compose newer then ver3 supports out of context build.
      # But, it doesn't support 'runtime'.
      # Therefore, context is root directory and this specifies dockerfile.
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - base_from=aten:latest
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    container_name: aten-docker
    runtime: nvidia
    environment:
      - "DISPLAY"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "../:/aten"
    network_mode: bridge
