version: "3.8"
services:
  aten:
    image: docker.io/aten/aten_dev:latest
    container_name: aten-docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - "DISPLAY"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "../:/aten"
    network_mode: bridge
