version: "2.4"
services:
  base:
    build:
      # docker-compose newer than ver3 supports out of context build.
      # But, it doesn't support 'runtime'.
      # Therefore, context specifies parent directory which is root directory,
      # and then this yaml file specifies the dockerfile as relative path from root.
      context: ..
      dockerfile: ./env/aten/Dockerfile
  aten:
    build:
      # docker-compose newer than ver3 supports out of context build.
      # But, it doesn't support 'runtime'.
      # Therefore, context specifies parent directory which is root directory,
      # and then this yaml file specifies the dockerfile as relative path from root.
      context: ..
      dockerfile: ./env/dev/Dockerfile
      args:
        - base_from=aten_devcontainer_base:latest
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    container_name: aten-docker
    runtime: nvidia
    environment:
      - "DISPLAY"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "../:/aten"
    network_mode: bridge
