name: 'Run git'
description: 'Run git command'
inputs:
  command:
    description: 'git command'
    required: true
outputs:
  result:
    description: 'result of git command'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
