name: 'Get Changed Files'
description: 'Saves lists of changed files as JSON for use by other actions.'
inputs:
  token:
    description: GitHub Personal Access Token
    required: true
outputs:
  all:
    description: Array of all changed files
  added:
    description: Array of added files
  deleted:
    description: Array of deleted files
  modified:
    description: Array of modified files
  renamed:
    description: Array of renamed files
runs:
  using: 'node12'
  main: 'dist/index.js'
    